### ISSUE TITLE
RFE: AUD conversion support via BitcoinAverage and BTCMarkets

### ISSUE THREAD

**Issue by syn-tax-err** [btcontract/olympus#4]
We’re a small Australian outreach group, demonstrating Bitcoin and Lightning payments to local small businesses. The in-app fiat conversion support is the most frequent request we get, and a critical requirement for adoption. 

AUD is well supported in https://github.com/knowm/XChange via the `bitcoinaverage` and `btcmarkets` connectors. It would be really appreciated if you could include it in the ExchangeRates class.

**Comment by btcontract** [comment]
Added to Olympus https://github.com/btcontract/olympus/commit/8d59b65f36702782079f5090150d64ef49c323e2 and BLW https://github.com/btcontract/lnwallet/commit/35f8f4cdbfe0c95db179b72374380be2a5d421f1, both will be updated soon.
